[project]
name = "pyamadon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyside6>=6.9.3",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.16.0",
]
